/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import javax.swing.JFrame;

/**
 *
 * @author Hyaci
 */
public class BMICalc extends javax.swing.JFrame {

    /**
     * Creates new form BMII
     */
    public BMICalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private WorkoutTimer workoutTimerInstance = null;
    private SleepTracker sleepTrackerInstance = null;
    private SleepTimer sleepTimerInstance = null;
    private BMICalc bmiCalcInstance = null;
    private MentalHealthInfoAppGUI infoSecInstance = null;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Weight = new javax.swing.JTextField();
        Height = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CBActivity = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BMI = new javax.swing.JTextField();
        RCI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Status = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MildWL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        WL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Calculatee = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        sleepMenu = new javax.swing.JMenu();
        timerItem = new javax.swing.JMenuItem();
        trackerItem = new javax.swing.JMenuItem();
        bmiMenu = new javax.swing.JMenu();
        workoutMenu = new javax.swing.JMenu();
        infoSecMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BMI & Calorie Intake Calculator");

        jLabel2.setText("Age:");

        jLabel3.setText("Gender:");

        jLabel4.setText("Height:");

        jLabel5.setText("Weight:");

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setText("Female");

        Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightActionPerformed(evt);
            }
        });

        jLabel7.setText("Activity:");

        CBActivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentary: little to no exercise/week", "Light: exercises 1-3 times/week", "Moderate: exercises 4-5 times/week", "Active: daily exercise/ intense exercise 3-5 times/week", "Very Acitve: intense exercise 6-7 times/week", "Extra Active: intense exercise daily/physical job" }));

        jLabel8.setText("cm");

        jLabel9.setText("kg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Age))
                                .addComponent(Female))
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Weight, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(Height))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(CBActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(Male)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Male)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Female)
                    .addComponent(CBActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Recommended Calorie Intake:");

        jLabel10.setText("BMI:");

        BMI.setEditable(false);

        RCI.setEditable(false);
        RCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCIActionPerformed(evt);
            }
        });

        jLabel11.setText("kg/m²");

        jLabel12.setText("Status:");

        Status.setEditable(false);
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });

        jLabel13.setText("calories/day");

        jLabel14.setText("To maintain weight:");

        MildWL.setEditable(false);
        MildWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MildWLActionPerformed(evt);
            }
        });

        jLabel15.setText("Mild Weight Loss (0.25kg/wk):");

        WL.setEditable(false);

        jLabel16.setText("Weight Loss (0.5kg/wk):");

        jLabel17.setText("calories/day");

        jLabel18.setText("calories/day");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RCI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(MildWL)
                            .addComponent(WL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(MildWL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(WL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Calculatee.setText("Calculate!");
        Calculatee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateeActionPerformed(evt);
            }
        });

        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        sleepMenu.setText("Sleep Timer");

        timerItem.setText("Sleep Timer");
        timerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(timerItem);

        trackerItem.setText("Sleep Tracker");
        trackerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(trackerItem);

        jMenuBar1.add(sleepMenu);

        bmiMenu.setText("BMI Calculator");
        bmiMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmiMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(bmiMenu);

        workoutMenu.setText("Workout Timer");
        workoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(workoutMenu);

        infoSecMenu.setText("Information Section");
        infoSecMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoSecMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(infoSecMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Calculatee)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculatee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void BCCalculate(){
        double weight = Double.parseDouble(Weight.getText()); // Weight in kg
        double height = Double.parseDouble(Height.getText()) / 100; // cm to meters
        int age = Integer.parseInt(Age.getText()); // Age
        String gender = Male.isSelected() ? "Male" : "Female";
        String activityLevel = (String) CBActivity.getSelectedItem();

        // Calculate BMI
        double bmi = weight / (height * height);
        BMI.setText(String.format("%.2f", bmi));

        double bmr;
        if (gender.equals("Male")) {
            bmr = 66 + (6.23 * weight) + (12.7 * height * 100) - (6.8 * age); // boi
        } else {
            bmr = 655 + (4.35 * weight) + (4.7 * height * 100) - (4.7 * age); // girl
        }

        double calorieIntake;
        switch (activityLevel) {
            case "Sedentary: little to no exercise/week":
                calorieIntake = bmr * 1.2;
                break;
            case "Light: exercises 1-3 times/week":
                calorieIntake = bmr * 1.375;
                break;
            case "Moderate: exercises 4-5 times/week":
                calorieIntake = bmr * 1.55;
                break;
            case "Active: daily exercise/intense exercise 3-5 times/week":
                calorieIntake = bmr * 1.725;
                break;
            case "Very Active: intense exercise 6-7 times/week":
                calorieIntake = bmr * 1.9;
                break;
            default:
                calorieIntake = bmr; 
                break;
        }

        RCI.setText(String.format("%.0f", calorieIntake)); // Cal intake
        
        if (bmi < 18.5) {
            Status.setText("Underweight");
        } else if (bmi < 24.9) {
            Status.setText("Normal weight");
        } else if (bmi < 29.9) {
            Status.setText("Overweight");
        } else {
            Status.setText("Obese");
        }
        
        //calorie deficit, weight L
        
        double caloriesPerKg = 7700; // Calories needed to lose 1 kg
        double mildWeightLoss = 0.25; // kg/week
        double regularWeightLoss = 0.5; // kg/week

        // Calculate daily deficit for mild weight loss
        double mildDailyDeficit = (mildWeightLoss * caloriesPerKg) / 7;
        MildWL.setText(String.format("%.0f", calorieIntake - mildDailyDeficit)); 

        // Calculate daily deficit for regular weight loss
        double regularDailyDeficit = (regularWeightLoss * caloriesPerKg) / 7;
        WL.setText(String.format("%.0f", calorieIntake - regularDailyDeficit)); 
    }
    
    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void RCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RCIActionPerformed

    private void CalculateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateeActionPerformed
        // TODO add your handling code here:
        BCCalculate();
    }//GEN-LAST:event_CalculateeActionPerformed

    private void MildWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MildWLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MildWLActionPerformed

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_homeMenuMouseClicked

    private void timerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerItemActionPerformed
        // TODO add your handling code here:
        if(sleepTimerInstance == null){
            sleepTimerInstance = new SleepTimer();
            sleepTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTimerInstance.setVisible(true);

            sleepTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }

            });
        }
    }//GEN-LAST:event_timerItemActionPerformed

    private void trackerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackerItemActionPerformed
        // TODO add your handling code here:
        if(sleepTrackerInstance == null){
            sleepTrackerInstance = new SleepTracker();
            sleepTrackerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTrackerInstance.setVisible(true);

            sleepTrackerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTrackerInstance = null;
                }

            });
        }
    }//GEN-LAST:event_trackerItemActionPerformed

    private void bmiMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiMenuMouseClicked
        // TODO add your handling code here:
        if(bmiCalcInstance == null){
            bmiCalcInstance = new BMICalc();
            bmiCalcInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bmiCalcInstance.setVisible(true);
            bmiCalcInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    bmiCalcInstance = null;
                }

            });
        }
    }//GEN-LAST:event_bmiMenuMouseClicked

    private void workoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutMenuMouseClicked
        // TODO add your handling code here:
        if(workoutTimerInstance == null){
            workoutTimerInstance = new WorkoutTimer();
            workoutTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            workoutTimerInstance.setVisible(true);

            workoutTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    workoutTimerInstance = null;
                }

            });
        }
    }//GEN-LAST:event_workoutMenuMouseClicked

    private void infoSecMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoSecMenuMouseClicked
        // TODO add your handling code here:
        if(infoSecInstance == null){
            infoSecInstance = new MentalHealthInfoAppGUI();
            infoSecInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            infoSecInstance.setVisible(true);

            infoSecInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }

            });
        }
    }//GEN-LAST:event_infoSecMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMICalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMICalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMICalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMICalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMICalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BMI;
    private javax.swing.JComboBox<String> CBActivity;
    private javax.swing.JButton Calculatee;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField Height;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField MildWL;
    private javax.swing.JTextField RCI;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField WL;
    private javax.swing.JTextField Weight;
    private javax.swing.JMenu bmiMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu infoSecMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu sleepMenu;
    private javax.swing.JMenuItem timerItem;
    private javax.swing.JMenuItem trackerItem;
    private javax.swing.JMenu workoutMenu;
    // End of variables declaration//GEN-END:variables
}
