package MyApp;


import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daphnie
 */
import javax.swing.*;
import java.awt.*;


class BackgroundLabel extends JLabel {
    private Image image;
   
    
    public BackgroundLabel() {
        image = new ImageIcon(getClass().getResource("/medibuddy.png")).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Draw the image scaled to the size of the label
        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
    }
}

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private WorkoutTimer workoutTimerInstance = null;
    private SleepTracker sleepTrackerInstance = null;
    private SleepTimer sleepTimerInstance = null;
    private BMICalc bmiCalcInstance = null;
    private MentalHealthInfoAppGUI infoSecInstance = null;
    private static Main mainInstance;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        sleepMenu = new javax.swing.JMenu();
        timerItem = new javax.swing.JMenuItem();
        trackerItem = new javax.swing.JMenuItem();
        bmiMenu = new javax.swing.JMenu();
        workoutMenu = new javax.swing.JMenu();
        infoSecMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/medibuddy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        sleepMenu.setText("Sleep Timer");

        timerItem.setText("Sleep Timer");
        timerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(timerItem);

        trackerItem.setText("Sleep Tracker");
        trackerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(trackerItem);

        jMenuBar1.add(sleepMenu);

        bmiMenu.setText("BMI Calculator");
        bmiMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmiMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(bmiMenu);

        workoutMenu.setText("Workout Timer");
        workoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(workoutMenu);

        infoSecMenu.setText("Information Section");
        infoSecMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoSecMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(infoSecMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void timerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerItemActionPerformed
          // TODO add your handling code here:
        if(sleepTimerInstance == null){
            sleepTimerInstance = new SleepTimer();
            sleepTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTimerInstance.setVisible(true);
            
            sleepTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {
                
                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }
                
            });
        }          
            
    }//GEN-LAST:event_timerItemActionPerformed

    private void trackerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackerItemActionPerformed
        // TODO add your handling code here:
        if(sleepTrackerInstance == null){
            sleepTrackerInstance = new SleepTracker();
            sleepTrackerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTrackerInstance.setVisible(true);
            
            sleepTrackerInstance.addWindowListener(new java.awt.event.WindowAdapter() {
                
                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTrackerInstance = null;
                }
                
            });
        }          
                    
    }//GEN-LAST:event_trackerItemActionPerformed

    private void workoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutMenuMouseClicked
        // TODO add your handling code here:
        if(workoutTimerInstance == null){
            workoutTimerInstance = new WorkoutTimer();
            workoutTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            workoutTimerInstance.setVisible(true);
           
            workoutTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {
                
                public void windowClosed(java.awt.event.WindowEvent e){
                    workoutTimerInstance = null;
                }
                
            });
       }               
    }//GEN-LAST:event_workoutMenuMouseClicked

    private void bmiMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiMenuMouseClicked
        // TODO add your handling code here:
        if(bmiCalcInstance == null){
            bmiCalcInstance = new BMICalc();
            bmiCalcInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bmiCalcInstance.setVisible(true);
            bmiCalcInstance.addWindowListener(new java.awt.event.WindowAdapter() {
                
                public void windowClosed(java.awt.event.WindowEvent e){
                    bmiCalcInstance = null;
                }
                
            });
        }
    }//GEN-LAST:event_bmiMenuMouseClicked

    private void infoSecMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoSecMenuMouseClicked
        // TODO add your handling code here:
        if(infoSecInstance == null){
            infoSecInstance = new MentalHealthInfoAppGUI();
            infoSecInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            infoSecInstance.setVisible(true);
            
            infoSecInstance.addWindowListener(new java.awt.event.WindowAdapter() {
                
                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }
                
            });
        }          
               
    }//GEN-LAST:event_infoSecMenuMouseClicked

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        // TODO add your handling code here:
//        if(mainInstance == null){
//            mainInstance = new Main();
//            mainInstance.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            mainInstance.setVisible(true);
//        }  
    }//GEN-LAST:event_homeMenuMouseClicked
    public static Main getMainInstance(){
        if(mainInstance == null){
            mainInstance = new Main();
        
        }
        return mainInstance;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bmiMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu infoSecMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu sleepMenu;
    private javax.swing.JMenuItem timerItem;
    private javax.swing.JMenuItem trackerItem;
    private javax.swing.JMenu workoutMenu;
    // End of variables declaration//GEN-END:variables
}
