package MyApp;


import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Molina
 */
public class WorkoutTimer extends javax.swing.JFrame {

    /**
     * Creates new form WorkoutTimer
     */
    private int min,sec;
        private Clip clip;
    private int m1,m2,m3,m4,m5;
    private int s1,s2,s3,s4,s5;
    private int currentInterval;
    private Timer timer;
    private String i1,i2,i3,i4,i5;
    public WorkoutTimer() {
        initComponents();
        populateCBox(min1,sec1);
        populateCBox(min2,sec2);
        populateCBox(min3,sec3);
        populateCBox(min4,sec4);
        populateCBox(min5,sec5);
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private WorkoutTimer workoutTimerInstance = null;
    private SleepTracker sleepTrackerInstance = null;
    private SleepTimer sleepTimerInstance = null;
    private BMICalc bmiCalcInstance = null;
    private MentalHealthInfoAppGUI infoSecInstance = null;
    private Main mainInstance= null;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intLabel = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        minLabel = new javax.swing.JLabel();
        secLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        interval1 = new javax.swing.JTextField();
        interval2 = new javax.swing.JTextField();
        interval3 = new javax.swing.JTextField();
        interval4 = new javax.swing.JTextField();
        interval5 = new javax.swing.JTextField();
        min1 = new javax.swing.JComboBox();
        sec1 = new javax.swing.JComboBox();
        min2 = new javax.swing.JComboBox();
        sec2 = new javax.swing.JComboBox();
        min3 = new javax.swing.JComboBox();
        min4 = new javax.swing.JComboBox();
        sec3 = new javax.swing.JComboBox();
        sec4 = new javax.swing.JComboBox();
        min5 = new javax.swing.JComboBox();
        sec5 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        sleepMenu = new javax.swing.JMenu();
        timerItem = new javax.swing.JMenuItem();
        trackerItem = new javax.swing.JMenuItem();
        bmiMenu = new javax.swing.JMenu();
        workoutMenu = new javax.swing.JMenu();
        infoSecMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        intLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        intLabel.setText(" ");
        intLabel.setMaximumSize(new java.awt.Dimension(615, 568));
        intLabel.setMinimumSize(new java.awt.Dimension(615, 568));

        minLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        minLabel.setText("00");

        secLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        secLabel.setText("00");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText(":");

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(minLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secLabel)
                .addGap(30, 30, 30))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minLabel)
                    .addComponent(secLabel)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25))
        );

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Intervals"));
        jPanel1.setAutoscrolls(true);

        jPanel2.setAutoscrolls(true);

        jLabel11.setText(":");

        jLabel13.setText(":");

        jLabel15.setText(":");

        jLabel17.setText(":");

        jLabel19.setText(":");

        interval1.setText("Interval 1");
        interval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interval1ActionPerformed(evt);
            }
        });

        interval2.setText("Interval 2");

        interval3.setText("Interval 3");

        interval4.setText("Interval 4");
        interval4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interval4ActionPerformed(evt);
            }
        });

        interval5.setText("Interval 5");
        interval5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interval5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(interval4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interval1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interval2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interval3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interval5, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(min1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(interval1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(interval2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(interval3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(interval4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(interval5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setText("Workout Interval Timer");
        jLabel5.setMaximumSize(new java.awt.Dimension(615, 568));
        jLabel5.setMinimumSize(new java.awt.Dimension(615, 568));

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        sleepMenu.setText("Sleep Timer");

        timerItem.setText("Sleep Timer");
        timerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(timerItem);

        trackerItem.setText("Sleep Tracker");
        trackerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackerItemActionPerformed(evt);
            }
        });
        sleepMenu.add(trackerItem);

        jMenuBar1.add(sleepMenu);

        bmiMenu.setText("BMI Calculator");
        bmiMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmiMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(bmiMenu);

        workoutMenu.setText("Workout Timer");
        workoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(workoutMenu);

        infoSecMenu.setText("Information Section");
        infoSecMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoSecMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(infoSecMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(stopButton)
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(resetButton)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        // TODO add your handling code here:
        getValues();
        checkInput();
        
        
    }//GEN-LAST:event_startButtonMouseClicked

    private void interval1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interval1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interval1ActionPerformed

    private void interval4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interval4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interval4ActionPerformed

    private void interval5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interval5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interval5ActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
        if(timer!= null && timer.isRunning()){
            timer.stop();
        }
        
        
    }//GEN-LAST:event_stopButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        s1 = 0;
        s2 = 0;
        s3 = 0;
        s4 = 0;
        s5 = 0;
        
        m1 = 0;
        m2 = 0;
        m3 = 0;
        m4 = 0;
        m5 = 0;
        
        i1 =null;
        i2 =null;
        i3 =null;
        i4 =null;
        i5 =null;
        
        min1.setSelectedIndex(0);
        min2.setSelectedIndex(0);
        min3.setSelectedIndex(0);
        min4.setSelectedIndex(0);
        min5.setSelectedIndex(0);
        
        sec1.setSelectedIndex(0);
        sec2.setSelectedIndex(0);
        sec3.setSelectedIndex(0);
        sec4.setSelectedIndex(0);
        sec5.setSelectedIndex(0);
        
        interval1.setText("Interval 1");
        interval2.setText("Interval 2");
        interval3.setText("Interval 3");
        interval4.setText("Interval 4");
        interval5.setText("Interval 5");
        
        minLabel.setText("00");
        secLabel.setText("00");
        intLabel.setText(null);
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_homeMenuMouseClicked

    private void timerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerItemActionPerformed
        // TODO add your handling code here:
        if(sleepTimerInstance == null){
            sleepTimerInstance = new SleepTimer();
            sleepTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTimerInstance.setVisible(true);

            sleepTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }

            });
        }

    }//GEN-LAST:event_timerItemActionPerformed

    private void trackerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackerItemActionPerformed
        // TODO add your handling code here:
        if(sleepTrackerInstance == null){
            sleepTrackerInstance = new SleepTracker();
            sleepTrackerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            sleepTrackerInstance.setVisible(true);

            sleepTrackerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTrackerInstance = null;
                }

            });
        }

    }//GEN-LAST:event_trackerItemActionPerformed

    private void bmiMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiMenuMouseClicked
        // TODO add your handling code here:
        if(bmiCalcInstance == null){
            bmiCalcInstance = new BMICalc();
            bmiCalcInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bmiCalcInstance.setVisible(true);
            bmiCalcInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    bmiCalcInstance = null;
                }

            });
        }
    }//GEN-LAST:event_bmiMenuMouseClicked

    private void workoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workoutMenuMouseClicked
        // TODO add your handling code here:
        if(workoutTimerInstance == null){
            workoutTimerInstance = new WorkoutTimer();
            workoutTimerInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            workoutTimerInstance.setVisible(true);

            workoutTimerInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    workoutTimerInstance = null;
                }

            });
        }
    }//GEN-LAST:event_workoutMenuMouseClicked

    private void infoSecMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoSecMenuMouseClicked
        // TODO add your handling code here:
        if(infoSecInstance == null){
            infoSecInstance = new MentalHealthInfoAppGUI();
            infoSecInstance.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            infoSecInstance.setVisible(true);

            infoSecInstance.addWindowListener(new java.awt.event.WindowAdapter() {

                public void windowClosed(java.awt.event.WindowEvent e){
                    sleepTimerInstance = null;
                }

            });
        }

    }//GEN-LAST:event_infoSecMenuMouseClicked

    private void checkInput(){
        int [] seconds = {s1,s2,s3,s4,s5};  //[3,0,4,0,5]
        int [] minutes = {m1,m2,m3,m4,m5};
        String [] intervalNames ={i1,i2,i3,i4,i5};
        boolean intDone=true;
        
        for(int i=currentInterval;i<5;i++){
            if(seconds[i]==0 &&minutes[i]==0){
              continue;
            }
            else{
                currentInterval=i;
                setIntLabel(intervalNames,i);
                startIntervalTimer(minutes[i],seconds[i],i);
                intDone=false;
                return;
            }
        }
        if(intDone){
        timer.stop();
        timer=null;
        JOptionPane.showMessageDialog(null,"Countdown Finished!","Timer Complete", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }
    
        private void playSound() {
        try {
            File soundFile = new File("alarm.wav"); // Specify the path to your audio file
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile);
            clip = AudioSystem.getClip(); // Get the Clip
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }

        private void stopSound() {
        if (clip != null && clip.isRunning()) {
            clip.stop(); // Stop the sound
            clip.close(); // Close the clip to release resources
        }
    }
    
    private void startIntervalTimer(int intMin, int intSec,int interval){
        
        if(timer!= null){
            timer.stop();
        }
            
        min=intMin;
        sec=intSec;
        
        
        secLabel.setText(String.format("%02d", sec));
        minLabel.setText(String.format("%02d", min));
        timer = new Timer(1000,new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
            if(sec ==0){
                if(min >0){
                    min--;
                    sec=59;
                }
                else{
                    secLabel.setText("00");
                    minLabel.setText("00");
                    
                    playSound();
                        JOptionPane.showMessageDialog(null, 
                        "Interval " + (interval + 1) + " is complete!", 
                        "Interval Complete", 
                        JOptionPane.INFORMATION_MESSAGE);
                        stopSound();
                        timer.stop();
                    currentInterval++;
                    checkInput();
                    return;
                }
          
            }
            

            sec--;
            secLabel.setText(String.format("%02d", sec));
            minLabel.setText(String.format("%02d", min));
            
        }
        
    });
        
    timer.start();
    }
    /**
     * @param args the command line arguments
     */
    
    private void getValues(){
    m1=Integer.parseInt(min1.getSelectedItem().toString());
    m2=Integer.parseInt(min2.getSelectedItem().toString());
    m3=Integer.parseInt(min3.getSelectedItem().toString());
    m4=Integer.parseInt(min4.getSelectedItem().toString());
    m4=Integer.parseInt(min5.getSelectedItem().toString());
    
    s1=Integer.parseInt(sec1.getSelectedItem().toString());
    s2=Integer.parseInt(sec2.getSelectedItem().toString());
    s3=Integer.parseInt(sec3.getSelectedItem().toString());
    s4=Integer.parseInt(sec4.getSelectedItem().toString());
    s5=Integer.parseInt(sec5.getSelectedItem().toString());
    
    
    i1 = interval1.getText();
    i2 = interval2.getText();
    i3 = interval3.getText();
    i4 = interval4.getText();
    i5 = interval5.getText();
    
    currentInterval=0;
    int [] minutes = {m1,m2,m3,m4,m5};
    int [] seconds = {s1,s2,s3,s4,s5};
    boolean allZero = true;
    for(int i =0; i<minutes.length;i++){
        if(minutes[i]!=0){
            allZero=false;
            break;
        }
    }
    for(int i=0; i<seconds.length;i++){
        if(seconds[i]!=0){
            allZero=false;
            break;
        }
    }
    
        if(allZero){
            JOptionPane.showMessageDialog(rootPane, "Please Try Again.","No Input Detected",0);
        }
    
    
   
    }
    private void setIntLabel(String [] nameArray,int f){
        
        if (nameArray[f].isEmpty()){

            intLabel.setText("Interval " +(f+1));
        }
        else{
        intLabel.setText(nameArray[f]);   
            
        }
        
    }
    
    public void populateCBox(JComboBox minBox,JComboBox secBox){
        for(int i = 0; i<60;i++){
            
            if(i<10){
                minBox.addItem("0"+i);
            }
            else{
            minBox.addItem(String.valueOf(i));
                
            }
        }
        for(int i=0; i<60;i++){
            if(i<10){
                secBox.addItem("0"+i);
            }
            else{
            secBox.addItem(String.valueOf(i));
                
            }
        }
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkoutTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bmiMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu infoSecMenu;
    private javax.swing.JLabel intLabel;
    private javax.swing.JTextField interval1;
    private javax.swing.JTextField interval2;
    private javax.swing.JTextField interval3;
    private javax.swing.JTextField interval4;
    private javax.swing.JTextField interval5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox min1;
    private javax.swing.JComboBox min2;
    private javax.swing.JComboBox min3;
    private javax.swing.JComboBox min4;
    private javax.swing.JComboBox min5;
    private javax.swing.JLabel minLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox sec1;
    private javax.swing.JComboBox sec2;
    private javax.swing.JComboBox sec3;
    private javax.swing.JComboBox sec4;
    private javax.swing.JComboBox sec5;
    private javax.swing.JLabel secLabel;
    private javax.swing.JMenu sleepMenu;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel timePanel;
    private javax.swing.JMenuItem timerItem;
    private javax.swing.JMenuItem trackerItem;
    private javax.swing.JMenu workoutMenu;
    // End of variables declaration//GEN-END:variables

}
